---
# tasks file for setup_web
- include_tasks: login_ecr.yml
  tags:
    - dev
    - stage
    - prod

- include_tasks: setup_git_repo.yml
  tags:
    - dev

- include_tasks: setup_tunnel.yml
  tags:
    - dev

- include_tasks: setup_nginx.yml
  tags:
    - stage
    - prod

- include_tasks: setup_build.yml
  vars:
    root: "~/{{ repo_name }}/client/build"
  tags:
    - dev

- include_tasks: setup_build.yml
  vars:
    root: "~"
  tags:
    - stage
    - prod

- include_tasks: start_server.yml
  vars:
    root: "~/{{ repo_name }}"
  tags:
    - dev

- include_tasks: start_server.yml
  vars:
    root: "~"
  tags:
    - stage
    - prod
