- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ root }}/nginx"
    state: directory
  tags:
    - setup

- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.{{ env }}.conf
    dest: "{{ root }}/nginx/nginx.conf"
  tags:
    - setup
