- name: Ensure build directory exists
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory
  tags:
    - setup

- name: Copy config.json
  ansible.builtin.template:
    src: "config.json.{{ env }}"
    dest: "{{ root }}/config.json"
  tags:
    - setup
