- name: Create databases
  command: docker-compose run --rm {{ item }} rake db:create
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - create
    - setup

- name: Migrate databases
  command: docker-compose run --rm {{ item }} rake db:migrate
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - create
    - setup

- name: Database dump
  command: docker run --rm --network host -v /home/{{ user_name }}:/tmp postgres:15 pg_dump -h localhost -U postgres -d auth_development -f /tmp/dump.sql
  tags:
    - dump

- name: Fetch dump file
  ansible.builtin.fetch:
    src: ~/tmp/dump.sql
    dest: ~/dump_files/dump.sql
    flat: yes
  tags:
    - dump

- name: Stop rails servers
  command: docker-compose stop {{ item }}
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - restore

- name: Drop databases
  command: docker-compose run --rm auth rake db:drop
  args:
    chdir: ~/sports-app
  tags:
    - restore

- name: Create databases
  command: docker-compose run --rm auth rake db:create
  args:
    chdir: ~/sports-app
  tags:
    - restore

- name: Copy dump file
  ansible.builtin.copy:
    src: ~/dump_files/dump.sql
    dest: ~/dump.sql
  tags:
    - restore

- name: Database restore
  command: docker run --rm --network host -v /home/{{ user_name }}:/tmp postgres:15 psql -h localhost -U postgres -d auth_development -f /tmp/dump.sql
  tags:
    - restore

- name: Start rails servers
  command: docker-compose start {{ item }}
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - restore
