- name: Create nginx directory
  ansible.builtin.file:
    path: ~/nginx
    state: directory
  tags:
    - setup

- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.{{ env }}.conf
    dest: ~/nginx/nginx.conf
  tags:
    - setup
