- name: Create nginx directory
  ansible.builtin.file:
    path: ~/{{ repo_name }}/nginx
    state: directory
  tags:
    - setup

- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.{{ env }}.conf
    dest: ~/{{ repo_name }}/nginx/nginx.conf
  tags:
    - setup
