- name: Copy build docker file to default file
  ansible.builtin.copy:
    src: "{{ root }}/docker-compose.build.yml"
    dest: "{{ root }}/docker-compose.yml"
    remote_src: yes
  tags:
    - dev

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.{{ env }}.yml
    dest: "{{ root }}/docker-compose.yml"
  tags:
    - stage
    - prod

- name: Copy secrets.env
  ansible.builtin.copy:
    src: secrets.env
    dest: "{{ root }}/secrets.env"
    mode: 0600
  tags:
    - setup

- name: Ensure secrets directory exists
  ansible.builtin.file:
    path: "{{ root }}/secrets"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
  tags:
    - stage
    - prod

- name: Copy digitalocean.ini
  ansible.builtin.template:
    src: digitalocean.ini
    dest: "{{ root }}/secrets/digitalocean.ini"
    mode: "0600"
  tags:
    - stage
    - prod

- name: Start Docker Compose containers
  community.general.docker_compose:
    project_src: "{{ root }}"
    build: yes
  environment:
    ENV: "{{ env }}"
  tags:
    - setup

- name: Add environment variable to user .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export ENV="{{ env }}"'
    create: yes
  tags:
    - setup
