- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.{{ env }}.yml
    dest: "{{ root }}/docker-compose.yml"
  tags:
    - dev

- name: Start Docker Compose containers
  community.general.docker_compose:
    project_src: "{{ root }}"
  tags:
    - dev
