---
# tasks file for setup_ansible

- name: Create a directory
  file:
    path: ~/.aws
    state: directory
    mode: 0755

- name: Copy AWS config
  copy:
    src: config
    dest: ~/.aws/config
    mode: 0600

- name: Copy AWS credentials
  copy:
    src: credentials
    dest: ~/.aws/credentials
    mode: 0600

- name: Copy private ssh key
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: Copy vault password text
  copy:
    src: ~/.vault_pass.txt
    dest: ~/.vault_pass.txt
    mode: 0600
