---
# tasks file for setup_ansible
- name: Update apt package cache (for Ubuntu)
  apt:
    update_cache: yes
  become: yes
  become_user: root
  tags:
    - setup

- name: Install Ansible dependencies
  apt:
    name:
      - ansible
      - python3-pip
      - ruby-bundler
    state: present
  register: result
  until: result is not failed
  retries: 5
  delay: 5
  become: yes
  become_user: root
  tags:
    - setup

- name: Install pip3 packages
  pip:
    name:
      - boto3
      - botocore
      - awscli
    executable: pip3
    state: present
  become: yes
  become_user: root
  tags:
    - setup

- name: Copy AWS configuration
  ansible.builtin.copy:
    src: ~/.aws
    dest: "~"
  tags:
    - setup

- name: Copy private ssh key
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
  tags:
    - setup

- name: Copy vault password text
  ansible.builtin.copy:
    src: ~/.vault_pass.txt
    dest: ~/.vault_pass.txt
  tags:
    - setup

- name: Copy files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "~"
  with_items:
    - requirements.txt
    - monitor_website.py
    - send_email.py
    - health_check.py
  tags:
    - setup

- name: Install Python packages from requirements file
  pip:
    requirements: ~/requirements.txt
  tags:
    - setup

- name: Add email variable to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: export EMAIL_ADDRESS={{ email_address }}
    state: present
  tags:
    - setup

- name: Add password variable to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: export EMAIL_PASSWORD={{ email_password }}
    state: present
  tags:
    - setup

- name: Deploy monitor service
  ansible.builtin.copy:
    dest: /etc/systemd/system/monitor_website.service
    content: |
      [Unit]
      Description=Monitor Website Script
      After=network.target

      [Service]
      ExecStart=/usr/bin/python3 /home/{{ user_name }}/monitor_website.py
      Restart=always
      User={{ user_name }}
      WorkingDirectory=/home/{{ user_name }}
      Environment="EMAIL_ADDRESS={{ email_address }}"
      Environment="EMAIL_PASSWORD={{ email_password }}"
      Restart=always
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target
  become_user: root
  become: yes
  tags:
    - setup

- name: Start and enable monitor service
  ansible.builtin.systemd:
    name: monitor_website
    enabled: true
    state: started
  become_user: root
  become: yes
  tags:
    - setup
