---
# tasks file for setup_ansible

- name: Copy AWS configuration
  copy:
    src: ~/.aws
    dest: "~"
    mode: 0600

- name: Copy private ssh key
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: Copy vault password text
  copy:
    src: ~/.vault_pass.txt
    dest: ~/.vault_pass.txt
    mode: 0600
