---
# tasks file for setup_ansible
- name: Update apt package cache (for Ubuntu)
  apt:
    update_cache: yes
  become: yes
  become_user: root
  tags:
    - setup

- name: Install Ansible dependencies
  apt:
    name:
      - ansible
      - python3-pip
      - ruby-bundler
    state: present
  register: result
  until: result is not failed
  retries: 5
  delay: 5
  become: yes
  become_user: root

- name: Install pip3 packages
  pip:
    name:
      - boto3
      - botocore
      - awscli
    executable: pip3
    state: present
  become: yes
  become_user: root
  tags:
    - setup

- name: Copy AWS configuration
  ansible.builtin.copy:
    src: ~/.aws
    dest: "~"

- name: Copy private ssh key
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
  tags:
    - setup

- name: Copy vault password text
  ansible.builtin.copy:
    src: ~/.vault_pass.txt
    dest: ~/.vault_pass.txt

- name: Copy files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "~"
  with_items:
    - requirements.txt
    - monitor_website.py
    - send_email.py
    - health_check.py
  tags:
    - setup

- name: Install Python packages from requirements file
  pip:
    requirements: ~/requirements.txt
  tags:
    - setup

- name: Add email variable to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: export EMAIL_ADDRESS={{ email_address }}
    state: present
  tags:
    - setup

- name: Add password variable to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: export EMAIL_PASSWORD={{ email_password }}
    state: present
  tags:
    - setup
