---
# tasks file for setup_web
- include_tasks: setup_git_repo.yml
  vars:
    branch_name: "alan/mercor-task-translation-encoding"
  tags:
    - mercor

- include_tasks: setup_tunnel.yml
  tags:
    - nercor

- include_tasks: start_server.yml
  vars:
    root: "~/chatwoot"
  tags:
    - mercor
