- name: Copy .env to new location
  ansible.builtin.copy:
    src: "{{ root }}/.env.example"
    dest: "{{ root }}/.env"
    remote_src: yes
  tags:
    - setup

- name: Start Docker Compose containers
  community.docker.docker_compose_v2:
    project_src: "{{ root }}"
    build: always
  environment:
    ENV: "{{ env }}"
  tags:
    - setup
