---
# handlers file for prometheus
- name: Reload Prometheus
  systemd:
    name: prometheus
    state: restarted

- name: Reload Node Exporter
  systemd:
    name: "node_exporter"
    state: restarted
