---
# tasks file for prometheus
- include_tasks: node_exporter.yml
- include_tasks: prometheus.yml

- name: Add the Grafana APT repository key
  ansible.builtin.shell: |
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add the Grafana APT repository
  ansible.builtin.shell: |
    sudo add-apt-repository -y "deb https://packages.grafana.com/oss/deb stable main"

- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
