version: "3.4"
services:
  client:
    image: "{{ ecr_repo_url }}/client:stage"
    environment:
      - HOST={{ ansible_host }}
      - PROTOCOL=http
    ports:
      - 80:80/tcp
    volumes:
      - ./nginx:/etc/nginx:ro
  server:
    image: "{{ ecr_repo_url }}/server:prod"
    ports:
      - 4000:4000
  auth:
    image: "{{ ecr_repo_url }}/auth:prod"
    env_file:
      - secrets.env
  football:
    image: "{{ ecr_repo_url }}/football:prod"
    env_file:
      - secrets.env
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:7.2.1-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
  postgres:
