version: "3.4"
services:
  client:
    image: "{{ ecr_repo_url }}/client:stage"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:ro
      - ./client/build/config.json:/usr/share/nginx/html/config.json:ro
      - letsencrypt:/etc/letsencrypt/
    environment:
      - STAGING=1
      - CERTBOT_EMAIL={{ email_address }}
    depends_on:
      - certbot
  certbot:
    image: certbot/dns-digitalocean
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./secrets:/etc/letsencrypt/secrets
    entrypoint: >
      sh -c "certbot certonly --force-renewal --dns-digitalocean --dns-digitalocean-credentials /etc/letsencrypt/secrets/digitalocean.ini --email {{ email_address }} --staging --agree-tos --no-eff-email -d {{ domain_name }}"
  server:
    image: "{{ ecr_repo_url }}/server:prod"
    ports:
      - 4000:4000
  auth:
    image: "{{ ecr_repo_url }}/auth:prod"
    env_file:
      - secrets.env
  football:
    image: "{{ ecr_repo_url }}/football:prod"
    env_file:
      - secrets.env
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:7.2.1-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
  postgres:
  letsencrypt:
