version: "3.4"
services:
  sidekiq:
    image: "{{ ecr_repo_url }}/football:prod"
    command: bundle exec sidekiq
    volumes:
      - ./football:/project
    environment:
      - REDIS_URL_SIDEKIQ=redis://{{ web_ip }}:6379/1
      - DB_HOST={{ web_ip }}
  crawler:
    image: "{{ ecr_repo_url }}/crawler:prod"
    volumes:
      - ./crawler:/project
    ports:
      - "5000:5000"
