---
- name: Create a new user
  user:
    name: "{{ user_name }}"
    groups:
      - sudo
    shell: /bin/bash
    state: present
  tags:
    - setup

- name: Create .ssh dir
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
  become: yes
  become_user: "{{ user_name }}"
  tags:
    - setup

- name: Copy SSH key for the new user
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    remote_src: yes
  become: yes
  tags:
    - setup

- name: Allow the new user to run sudo without a password prompt
  lineinfile:
    path: /etc/sudoers
    line: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  tags:
    - setup
