jenkins:
  systemMessage: Welcome to our Jenkins CI/CD Server
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "{{ jenkins_user }}"
          password: "{{ jenkins_password }}"
jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://github.com/alancovarrubias/sports-app.git'
            }
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "alancovarrubias"
              password: "password"
              description: "GitHub Token"
