jenkins:
  systemMessage: "Welcome to our Jenkins CI/CD Server"
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "youradminpassword"
