---
# tasks file for setup_monitoring
- name: Ensure the directory exists
  file:
    path: "{{ monitoring_home }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: Create Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: "{{ monitoring_home }}/prometheus.yml"

- name: Copy rules config
  ansible.builtin.template:
    src: rules.yml
    dest: "{{ monitoring_home }}/rules.yml"

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ monitoring_home }}/docker-compose.yml"

- name: Start Docker Compose containers
  community.general.docker_compose:
    project_src: "{{ monitoring_home }}"
    restarted: true
