---
# tasks file for setup_monitoring
- name: Ensure the directory exists
  ansible.builtin.file:
    path: "{{ monitoring_home }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
  tags:
    - server
    - client

- name: Create Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: "{{ monitoring_home }}/prometheus.yml"
  tags:
    - server

- name: Create Alertmanager configuration file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: "{{ monitoring_home }}/alertmanager.yml"
  tags:
    - server

- name: Copy rules config
  ansible.builtin.template:
    src: rules.yml
    dest: "{{ monitoring_home }}/rules.yml"
  tags:
    - server

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.server.yml
    dest: "{{ monitoring_home }}/docker-compose.yml"
  tags:
    - server

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.client.yml
    dest: "{{ monitoring_home }}/docker-compose.yml"
  tags:
    - client

- name: Start Docker Compose containers
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_home }}"
    restarted: true
  tags:
    - server
    - client
