---
# tasks file for setup_monitoring
- include_tasks: prometheus.yml
- include_tasks: node_exporter.yml
- include_tasks: grafana.yml
- include_tasks: alertmanager.yml

- name: Wait for Grafana to start
  wait_for:
    port: 3000
  tags:
    - test

- name: Install Grafana data source - Prometheus
  uri:
    url: "http://{{ target_host_ip }}:3000/api/datasources"
    method: POST
    body_format: json
    body: '{"name":"Prometheus","type":"prometheus","url":"{{ prometheus_endpoint }}","access":"proxy"}'
    user: admin
    password: admin
    force_basic_auth: true
  tags:
    - test
