---
# tasks file for setup_monitoring
- include_tasks: prometheus.yml
- include_tasks: node_exporter.yml
- include_tasks: grafana.yml
- include_tasks: alertmanager.yml

- name: Wait for Grafana to start
  wait_for:
    port: 3000
  tags:
    - test

- name: Check if {{ datasource_name }} data source already exists
  uri:
    url: "{{ grafana_endpoint }}/api/datasources/name/{{ datasource_name }}"
    method: GET
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  register: prometheus_data_source_result
  ignore_errors: true
  tags:
    - test

- name: Install Grafana data source - Prometheus
  uri:
    url: "{{ grafana_endpoint }}/api/datasources"
    method: POST
    body_format: json
    body: "{{ lookup('template', 'datasource_file.json') }}"
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  when: "prometheus_data_source_result.status == 404"
  tags:
    - test

- name: Get Grafana dashboards
  uri:
    url: "{{ grafana_endpoint }}/api/search"
    method: GET
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  register: grafana_dashboards_result
  tags:
    - test

- name: Set dashboard names
  set_fact:
    dashboard_names: "{{ grafana_dashboards_result.json | map(attribute='title') }}"
  tags:
    - test

- name: Import Grafana dashboard
  uri:
    url: "{{ grafana_endpoint }}/api/dashboards/db"
    method: POST
    body_format: json
    body: "{{ lookup('template', 'dashboard_file.json') }}"
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  when: "dashboard_name not in dashboard_names"
  tags:
    - test
