---
# tasks file for setup_monitoring
- include_tasks: prometheus.yml
- include_tasks: node_exporter.yml
- include_tasks: grafana.yml
- include_tasks: alertmanager.yml

- name: Wait for Grafana to start
  wait_for:
    port: 3000
  tags:
    - test

- name: Check if Prometheus data source already exists
  uri:
    url: "http://{{ target_host_ip }}:3000/api/datasources/name/Prometheus"
    method: GET
    headers:
      Content-Type: "application/json"
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  register: prometheus_data_source_result
  ignore_errors: true
  tags:
    - test

- name: Install Grafana data source - Prometheus
  uri:
    url: "http://{{ target_host_ip }}:3000/api/datasources"
    method: POST
    body_format: json
    body: '{"name":"Prometheus","type":"prometheus","url":"{{ prometheus_endpoint }}","access":"proxy"}'
    user: admin
    password: admin
    force_basic_auth: true
  when: "prometheus_data_source_result.status == 404"
  tags:
    - test

- name: Import Grafana dashboard
  uri:
    url: "http://{{ target_host_ip }}:3000/api/dashboards/db"
    method: POST
    body_format: json
    body: "{{ lookup('file', 'dashboard_file.json') }}"
    user: admin
    password: admin
    force_basic_auth: true
  register: import_result
  tags:
    - test

- name: Debug import result
  debug:
    var: import_result.json
  tags:
    - test
