- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Create Prometheus configuration file
  template:
    src: prometheus.yml
    dest: "{{ prometheus_config_path }}/prometheus.yml"
  notify: Reload Prometheus

- name: Copy rules config
  ansible.builtin.template:
    src: rules.yml
    dest: "{{ prometheus_config_path }}/rules.yml"

- name: Set up Prometheus as a systemd service
  systemd:
    name: prometheus
    enabled: yes
    state: started
  notify: Reload Prometheus
