---
- name: Run psql command in Docker container
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute psql command in Docker container
      ansible.builtin.command: >
        docker exec -i alan_db_1 bash -c "pg_dump -U postgres football_production > /tmp/dump.sql"

    - name: Copy dump file from container to local machine
      ansible.builtin.command: >
        docker cp alan_db_1:/tmp/dump.sql /home/alan/dump.sql

    - name: Fetch the file
      ansible.builtin.fetch:
        src: /home/alan/dump.sql
        dest: /Users/alancovarrubias/dump.sql
        flat: yes
