---
- name: Copy .git-credentials
  copy:
    src: .git-credentials
    dest: "~"
    mode: 0600
  tags:
    - setup

- name: Copy gitconfig
  copy:
    src: ~/.gitconfig
    dest: "~"
  tags:
    - setup
