version: "3.4"
services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
  node-exporter:
    image: quay.io/prometheus/node-exporter
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD={{ grafana_admin_password }}
    depends_on:
      - prometheus