---
- name: Setup jenkins
  hosts: all
  gather_facts: false
  roles:
    - setup_server
    - setup_docker
    - setup_jenkins

- name: Create SSH Config File
  hosts: localhost
  roles:
    - role: setup_ssh_config
      vars:
        server_name: "jenkins_server"
        env_var: "JENKINS_IP"
        user_name: "alan"
