---
- name: Wait for ssh connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure ssh port open
      ansible.builtin.wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        delay: 10
      vars:
        ansible_connection: local

- import_playbook: install_docker.yml

- name: Create a new user and disable root access
  hosts: all
  become: true
  vars_files:
    - project-vars
  tasks:
    - name: Create a new user
      user:
        name: "{{user_name}}"
        groups:
          - sudo
          - docker
        shell: /bin/bash
        state: present

    - name: Copy SSH key for the new user
      authorized_key:
        user: "{{user_name}}"
        key: "{{ lookup('file', '/Users/alancovarrubias/.ssh/id_rsa.pub') }}"
        state: present

    - name: Allow the new user to run sudo without a password prompt
      lineinfile:
        path: /etc/sudoers
        line: "{{user_name}} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
