---
- name: Setup ansible
  hosts: all
  gather_facts: true
  gather_timeout: 120
  roles:
    - role: setup_ssh_config
      vars:
        server_name: "ansible_server"
        env_var: "ANSIBLE_IP"
    - setup_server
    - setup_ansible
