---
- name: Create SSH Config File
  hosts: localhost
  tasks:
    - name: Generate SSH Config File
      template:
        src: ssh_config
        dest: "{{ ansible_env.HOME }}/.ssh/config"
      vars:
        target_host_ip: "{{ target_host_ip }}"

    - name: Adding the path in the zshrc files
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.zshrc"
        regexp: ^export DROPLET_IP=
        line: export DROPLET_IP={{ target_host_ip }}
        state: present

- name: Setup server
  hosts: all
  gather_facts: false
  roles:
    - setup_server
    - jenkins
