---
- name: Install ansible
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - setup_docker
    - role: setup_ssh_config
      vars:
        server_name: "ansible"
        env_var: "ANSIBLE_IP"

- name: Setup ansible
  hosts: all
  gather_facts: no
  become: true
  become_user: "{{ user_name }}"
  vars_files:
    - secret_vars.yml
  roles:
    - setup_monitoring
