---
- name: Wait for ssh connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure ssh port open
      ansible.builtin.wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        delay: 10
      vars:
        ansible_connection: local

- import_playbook: install_docker.yml

- name: Create new linux user
  hosts: all
  become: true
  vars_files:
    - project-vars
  tasks:
    - name: Create new linux user
      user:
        name: "{{user_name}}"
        groups: docker
