---
- name: Setup jenkins
  hosts: all
  gather_facts: true
  gather_timeout: 120
  roles:
    - role: setup_ssh_config
      vars:
        server_name: "jenkins_server"
        env_var: "JENKINS_IP"
    - setup_server
    - setup_docker
    - setup_jenkins
