- name: Setup server
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - setup_docker
    - role: setup_ssh_config
      vars:
        server_name: "dev"
        env_var: "DEV_IP"
  tasks:
    - name: get ECR password
      shell: "aws ecr get-login-password --region {{ aws_region }}"
      register: ecr_password
      delegate_to: localhost

- name: Setup sports app dev
  hosts: all
  gather_facts: no
  become: yes
  become_user: "{{ user_name }}"
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/alancovarrubias/sports-app.git
        dest: "~/sports-app"
        update: yes

    - name: Copy docker compose
      ansible.builtin.template:
        src: docker-compose.yml
        dest: "~/sports-app"

    - name: Docker repository login
      docker_login:
        registry_url: https://{{ ecr_repo_url }}
        username: AWS
        password: "{{ ecr_password.stdout }}"

    - name: Start Docker Compose containers
      community.general.docker_compose:
        project_src: "~/sports-app"
