---
- name: Setup ansible server
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - setup_docker
    - role: setup_ssh_config
      vars:
        server_name: "jenkins"
        env_var: "JENKINS_IP"

- name: Setup jenkins
  hosts: all
  gather_facts: no
  become: true
  become_user: "{{ user_name }}"
  roles:
    - setup_jenkins
