---
- name: Install ansible
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - role: setup_ssh_config
      vars:
        server_name: "ansible"
        env_var: "ANSIBLE_IP"
  tasks:
    - name: Update apt package cache (for Ubuntu)
      apt:
        update_cache: yes

    - name: Install Ansible dependencies
      apt:
        name:
          - ansible
          - python3-pip
          - ruby-bundler
        state: present
      register: result
      until: result is not failed
      retries: 5
      delay: 5

    - name: Install pip3 packages
      pip:
        name:
          - boto3
          - botocore
          - awscli
        executable: pip3
        state: present

- name: Setup ansible
  hosts: all
  gather_facts: no
  become: true
  become_user: "{{ user_name }}"
  tasks:
    - name: Copy AWS configuration
      copy:
        src: ~/.aws
        dest: "~"
        mode: 0600

    - name: Copy private ssh key
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        mode: 0600

    - name: Copy vault password text
      copy:
        src: ~/.vault_pass.txt
        dest: ~/.vault_pass.txt
        mode: 0600
