- name: Setup server
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - setup_docker
    - role: setup_ssh_config
      vars:
        server_name: "worker"
        env_var: "WORKER_IP"

- name: Setup sports app worker
  hosts: all
  gather_facts: no
  become: yes
  become_user: "{{ user_name }}"
  roles:
    - setup_worker
    - setup_monitoring
