---
- name: Create SSH Config File
  hosts: localhost
  roles:
    - role: setup_ssh_config
      vars:
        server_name: "ansible_server"
        env_var: "ANSIBLE_IP"

- name: Setup ansible
  hosts: all
  gather_facts: false
  roles:
    - setup_server
    - setup_ansible
