---
# vars file for setup_monitoring
user_name: alan
user_home: /home/{{ user_name }}
prometheus_endpoint: http://{{ target_host_ip }}:9090
webhook_url: https://webhook.site/24bc2ba6-18ec-4ae9-ac08-627d5307e712
grafana_admin_user: admin
grafana_admin_password: admin
grafana_endpoint: http://{{ target_host_ip }}:3000
datasource_name: Prometheus
bytes_in_gb: 1000000000
