---
- hosts: all
  remote_user: ec2-user
  become: true
  tasks:
    - name: checking updates
      yum:
        security: yes
        state: latest

    - name: Install git
      ansible.builtin.yum:
        name: git
        state: latest

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/alancovarrubias/sports-app
        dest: /home/ec2-user/sports-app

    - name: install pre-requisites
      pip:
        name:
          - docker
          - docker-compose

    - name: Install the latest version of Docker
      ansible.builtin.yum:
        name: docker
        state: latest

    - name: Ensure docker daemon is running
      service:
        name: docker
        state: started

    - name: Add the user 'ec2-user' with a specific uid and a primary group of 'docker'
      ansible.builtin.user:
        name: ec2-user
        group: docker

    # - name: Create and start services
    #   docker_compose:
    #     project_src: sports-app
    #   register: output
    #   tags: build
