version: "3.4"
services:
  jenkins:
    image: custom-jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    env_file:
      - .env
      - secrets.env
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/{{ user_name }}/casc_configs:/var/jenkins_home/casc_configs
      - /home/{{ user_name }}/.ssh:/var/jenkins_home/.ssh

volumes:
  jenkins_home:
