---
# tasks file for jenkins
- name: Copy docker compose
  copy:
    src: docker-compose.yml
    dest: /home/{{ user_name }}/docker-compose.yml
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Copy secrets.env
  copy:
    src: secrets.env
    dest: /home/{{ user_name }}/secrets.env
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Copy .env
  ansible.builtin.template:
    src: .env
    dest: /home/{{ user_name }}/.env
  tags:
    - jenkins

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/{{ user_name }}/Dockerfile
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  register: Dockerfile_info
  tags:
    - jenkins

- name: Copy plugins.txt
  copy:
    src: plugins.txt
    dest: /home/{{ user_name }}/plugins.txt
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  register: plugins_info
  tags:
    - jenkins

- name: Copy AWS config
  copy:
    src: config
    dest: /home/{{ user_name }}/config
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Copy AWS credentials
  copy:
    src: credentials
    dest: /home/{{ user_name }}/credentials
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Create a casc_configs directory
  file:
    path: /home/{{ user_name }}/casc_configs
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  tags:
    - jenkins

- name: Copy jenkins.yaml
  ansible.builtin.template:
    src: jenkins.yaml
    dest: /home/{{ user_name }}/casc_configs/jenkins.yaml
  tags:
    - jenkins

- name: Copy private ssh key
  copy:
    src: ~/.ssh/id_rsa
    dest: /home/{{ user_name }}/.ssh/id_rsa
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Change docker.sock permissions
  file:
    path: /var/run/docker.sock
    mode: 666
  tags:
    - jenkins

- name: Build Docker Image
  community.general.docker_image:
    name: custom-jenkins
    tag: latest
    build:
      path: /home/{{ user_name }}
    source: build
    force_source: "{{ plugins_info.changed or Dockerfile_info.changed }}"
  tags:
    - jenkins

- name: Start Docker Compose containers
  community.general.docker_compose:
    project_src: /home/{{ user_name }}"
    restarted: true
  tags:
    - jenkins

- name: Output plugins
  shell: |
    JENKINS_HOST={{ jenkins_user }}:{{ jenkins_password }}@{{ ansible_host }}:{{ jenkins_port }}
    curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" |
      perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g' |
      sed 's/ /:/'
  delegate_to: localhost
  register: plugin_versions
  tags:
    - plugins

- name: Write new plugins file
  copy:
    content: "{{ plugin_versions.stdout }}"
    dest: ~/Projects/sports-app-infra/ansible/setup_jenkins/files/plugins.txt
  delegate_to: localhost
  tags:
    - plugins
