---
# tasks file for jenkins
- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/docker-compose.yml
    mode: 0600
  tags:
    - jenkins

- name: Copy secrets.env
  copy:
    src: secrets.env
    dest: ~/secrets.env
    mode: 0600
  tags:
    - jenkins

- name: Copy .env
  ansible.builtin.template:
    src: .env
    dest: ~/.env
  tags:
    - jenkins

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: ~/Dockerfile
    mode: 0600
  register: Dockerfile_info
  tags:
    - jenkins

- name: Copy plugins.txt
  copy:
    src: plugins.txt
    dest: ~/plugins.txt
    mode: 0600
  register: plugins_info
  tags:
    - jenkins

- name: Copy AWS configuration
  copy:
    src: ~/.aws
    dest: "~"
    mode: 0600
  tags:
    - jenkins

- name: Create a casc_configs directory
  file:
    path: ~/casc_configs
    state: directory
    mode: 0755
  tags:
    - jenkins

- name: Copy jenkins.yaml
  ansible.builtin.template:
    src: jenkins.yaml
    dest: ~/casc_configs/jenkins.yaml
  tags:
    - jenkins

- name: Copy private ssh key
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600
  tags:
    - jenkins

- name: Build Docker Image
  community.general.docker_image:
    name: custom-jenkins
    tag: latest
    build:
      path: "~"
    source: build
    force_source: "{{ plugins_info.changed or Dockerfile_info.changed }}"
  tags:
    - jenkins

- name: Start Docker Compose containers
  community.docker.docker_compose_v2:
    project_src: "~"
  tags:
    - jenkins

- name: Output plugins
  shell: |
    JENKINS_HOST={{ jenkins_user }}:{{ jenkins_password }}@{{ ansible_host }}:{{ jenkins_port }}
    curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" |
      perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g' |
      sed 's/ /:/'
  delegate_to: localhost
  register: plugin_versions
  tags:
    - plugins
# - name: Write new plugins file
#   copy:
#     content: "{{ plugin_versions.stdout }}"
#     dest: ~/Projects/{{ infra_repo_name }}/ansible/setup_jenkins/files/plugins.txt
#   delegate_to: localhost
#   tags:
#     - plugins
