---
# tasks file for jenkins
- name: Copy docker compose
  copy:
    src: docker-compose.yml
    dest: "{{ user_home }}/docker-compose.yml"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Copy secrets.env
  copy:
    src: secrets.env
    dest: "{{ user_home }}/secrets.env"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Copy .env
  ansible.builtin.template:
    src: .env
    dest: "{{ user_home }}/.env"
  tags:
    - jenkins

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ user_home }}/Dockerfile"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  register: Dockerfile_info
  tags:
    - jenkins

- name: Copy plugins.txt
  copy:
    src: plugins.txt
    dest: "{{ user_home }}/plugins.txt"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  register: plugins_info
  tags:
    - jenkins

- name: Copy AWS config
  copy:
    src: config
    dest: "{{ user_home }}/config"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Copy AWS credentials
  copy:
    src: credentials
    dest: "{{ user_home }}/credentials"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  tags:
    - jenkins

- name: Create a casc_configs directory
  file:
    path: "{{ user_home }}/casc_configs"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  tags:
    - jenkins

- name: Copy jenkins.yaml
  ansible.builtin.template:
    src: jenkins.yaml
    dest: "{{ user_home }}/casc_configs/jenkins.yaml"
  tags:
    - jenkins

- name: Run ssh-keygen if key doesn't exist
  command: "ssh-keygen -t rsa -b 2048 -N '' -f {{ user_home }}/.ssh/id_rsa"
  become: yes
  become_user: "{{ user_name }}"
  args:
    creates: "{{ user_home }}/.ssh/id_rsa"
  tags:
    - jenkins

- name: Copy public key to local machine
  ansible.builtin.fetch:
    src: "{{ user_home }}/.ssh/id_rsa.pub"
    dest: ~/.ssh/jenkins.pub
    flat: yes
  tags:
    - jenkins

- name: Add public key to ansible authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '~/.ssh/jenkins.pub') }}"
    state: present
  delegate_to: "{{ ansible_ip }}"
  tags:
    - jenkins

- name: Change docker.sock permissions
  file:
    path: /var/run/docker.sock
    mode: 666
  tags:
    - jenkins

- name: Build Docker Image
  community.general.docker_image:
    name: custom-jenkins
    tag: latest
    build:
      path: "{{ user_home }}"
    source: build
    force_source: "{{ plugins_info.changed or Dockerfile_info.changed }}"
  tags:
    - jenkins

- name: Start Docker Compose containers
  community.general.docker_compose:
    project_src: "{{ user_home }}"
    restarted: true
  tags:
    - jenkins

- name: Output plugins
  shell: |
    JENKINS_HOST={{ jenkins_user }}:{{ jenkins_password }}@{{ target_host_ip }}:{{ jenkins_port }}
    curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" |
      perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g' |
      sed 's/ /:/'
  delegate_to: localhost
  register: plugin_versions
  tags:
    - plugins

- name: Write new plugins file
  copy:
    content: "{{ plugin_versions.stdout }}"
    dest: ~/Projects/sports-app-infra/ansible/setup_jenkins/files/plugins.txt
  delegate_to: localhost
  tags:
    - plugins
