---
# tasks file for setup_sports_app_dev
- name: Copy gitconfig
  copy:
    src: ~/.gitconfig
    dest: "~"

- name: Check if repo exists
  stat:
    path: ~/sports-app
  register: repo_check

- name: Clone Git Repository
  git:
    repo: https://github.com/alancovarrubias/sports-app.git
    dest: ~/sports-app
    update: yes
  when: not repo_check.stat.exists

- name: Find PID of ssh tunnel
  shell: "pgrep -f 'ssh -fN -L'"
  register: tunnel_pid
  ignore_errors: true # Ignore errors if the process is not found
  become_user: "{{ local_user }}"
  become: yes
  delegate_to: localhost
  tags:
    - tunnel

- name: Terminate ssh tunnel
  shell: "kill -TERM {{ tunnel_pid.stdout }}"
  when: tunnel_pid.stdout != ''
  become_user: "{{ local_user }}"
  become: yes
  delegate_to: localhost
  tags:
    - tunnel

- name: Copy tunnel script
  ansible.builtin.template:
    src: tunnel.sh
    dest: ~/tunnel.sh
    mode: 0700
  become_user: "{{ local_user }}"
  become: yes
  delegate_to: localhost
  tags:
    - tunnel

- name: Run tunnel script
  command: ~/tunnel.sh
  become_user: "{{ local_user }}"
  become: yes
  delegate_to: localhost
  tags:
    - tunnel

- name: get ECR password
  shell: "aws ecr get-login-password --region {{ aws_region }}"
  register: ecr_password
  delegate_to: localhost
  become_user: "{{ local_user }}"
  become: yes
  tags:
    - deploy

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/sports-app
  tags:
    - deploy

- name: Docker repository login
  docker_login:
    registry_url: https://{{ ecr_repo_url }}
    username: AWS
    password: "{{ ecr_password.stdout }}"
  tags:
    - deploy

- name: Start Docker Compose containers
  community.general.docker_compose:
    project_src: ~/sports-app
  tags:
    - deploy

- name: Create databases
  command: docker-compose run --rm {{ item }} rake db:create
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - db

- name: Migrate databases
  command: docker-compose run --rm {{ item }} rake db:migrate
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - db

- name: Database dump
  command: docker run --rm --network host -v /home/{{ user_name }}:/tmp postgres:15 pg_dump -h localhost -U postgres -d auth_development -f /tmp/dump.sql
  tags:
    - dump
    - skip

- name: Fetch dump file
  ansible.builtin.fetch:
    src: ~/tmp/dump.sql
    dest: ~/dump_files/dump.sql
    flat: yes
  tags:
    - dump
    - skip

- name: Stop rails servers
  command: docker-compose stop {{ item }}
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - restore
    - skip

- name: Drop databases
  command: docker-compose run --rm auth rake db:drop
  args:
    chdir: ~/sports-app
  tags:
    - restore
    - skip

- name: Create databases
  command: docker-compose run --rm auth rake db:create
  args:
    chdir: ~/sports-app
  tags:
    - restore
    - skip

- name: Copy dump file
  ansible.builtin.copy:
    src: ~/dump_files/dump.sql
    dest: ~/dump.sql
  tags:
    - restore
    - skip

- name: Database restore
  command: docker run --rm --network host -v /home/alan:/tmp postgres:15 psql -h localhost -U postgres -d auth_development -f /tmp/dump.sql
  tags:
    - restore
    - skip

- name: Start rails servers
  command: docker-compose start {{ item }}
  args:
    chdir: ~/sports-app
  loop:
    - auth
    - football
  tags:
    - restore
    - skip
