apiVersion: v1
kind: Secret
metadata:
  name: database-url
type: Opaque
stringData:
  DATABASE_URL: "{{ database_url }}"
  AUTH_DATABASE_URL: "{{ auth_database_url }}"
  FOOTBALL_DATABASE_URL: "{{ football_database_url }}"
